/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

'use strict';

function sum(){
  let current = 0;
  let first = 1;
  let second = 2;
  let temp;
  let answer = 2;

  while(current < 4000000){
    temp = first + second;
    if(temp % 2 === 0){
      answer += temp;
    }
    first = second;
    second = temp;
    current = temp;
  }

  console.log(answer);
}

sum();
